version: "3.2"

services:
  dev:
    container_name: node-template
    image: oodlesofmoodles/hmt:latest
    ports:
      - 9944:9944
    volumes:
      - .:/var/www/node-template
      - type: bind
        source: ./.local
        target: /root/.local
    command:
      node-template --dev --ws-external
